#!/usr/bin/env bash
# setup-confluence.sh
#
# Automates Confluence Data Center setup AFTER the license step has been
# completed in the browser.
#
# Run AFTER:
#   1. Opening http://localhost:30090 in a browser
#   2. Entering the Confluence Data Center license key
#   3. Choosing "Data Center" install type (not Server)
#
# What this script does:
#   - Waits for Confluence to finish its post-license DB initialisation
#   - Configures the database connection (skipped — already injected via Helm)
#   - Creates the admin user (admin / admin)
#   - Creates the Team Penta space (key: PENTA)
#   - Seeds four knowledge-base pages (Kafka, Redis, Zookeeper, Vault)
#   - Writes the .env file for the scraper
#
# Prerequisites: curl, base64 (coreutils), jq
# Usage: bash k8s/setup-confluence.sh

set -euo pipefail

BASE_URL="http://localhost:30090"
ADMIN_USER="admin"
ADMIN_PASS="admin"
SPACE_KEY="PENTA"
SPACE_NAME="Team Penta"
AUTH_HEADER="Authorization: Basic $(echo -n "${ADMIN_USER}:${ADMIN_PASS}" | base64)"

log() { echo "[setup] $*" >&2; }

wait_for_confluence() {
  log "Waiting for Confluence to finish post-license setup..."
  local max=60 count=0
  while true; do
    http_code=$(curl -s -o /dev/null -w "%{http_code}" -u "${ADMIN_USER}:${ADMIN_PASS}" \
      "${BASE_URL}/rest/api/space" 2>/dev/null || echo "000")
    if [[ "$http_code" == "200" ]]; then
      log "Confluence REST API is responding."
      return 0
    fi
    count=$((count + 1))
    if [[ $count -ge $max ]]; then
      log "ERROR: Confluence REST API did not become ready after ${max} attempts."
      exit 1
    fi
    log "  HTTP $http_code — waiting 10s (attempt $count/$max)..."
    sleep 10
  done
}

create_space() {
  log "Creating space: ${SPACE_NAME} (${SPACE_KEY})..."
  local resp
  resp=$(curl -s -w "\n%{http_code}" -X POST \
    -H "Content-Type: application/json" \
    -H "${AUTH_HEADER}" \
    "${BASE_URL}/rest/api/space" \
    -d "{
      \"key\": \"${SPACE_KEY}\",
      \"name\": \"${SPACE_NAME}\",
      \"description\": {
        \"plain\": {
          \"value\": \"Team Penta knowledge base — Kafka, Redis, Zookeeper, Vault operational guides.\",
          \"representation\": \"plain\"
        }
      }
    }")
  local body http_code
  body=$(echo "$resp" | head -n -1)
  http_code=$(echo "$resp" | tail -n 1)
  if [[ "$http_code" == "200" || "$http_code" == "201" ]]; then
    log "Space created successfully."
  elif echo "$body" | grep -q "already exists\|SPACE_ALREADY_EXISTS\|space with key"; then
    log "Space ${SPACE_KEY} already exists — continuing."
  else
    log "ERROR creating space: HTTP $http_code — $body"
    exit 1
  fi
}

create_page() {
  local title="$1"
  local body_storage="$2"
  log "Creating page: ${title}..."
  local resp
  resp=$(curl -s -w "\n%{http_code}" -X POST \
    -H "Content-Type: application/json" \
    -H "${AUTH_HEADER}" \
    "${BASE_URL}/rest/api/content" \
    -d "$(jq -n \
      --arg title "$title" \
      --arg space "$SPACE_KEY" \
      --arg body  "$body_storage" \
      '{
        type: "page",
        title: $title,
        space: { key: $space },
        body: {
          storage: {
            value: $body,
            representation: "storage"
          }
        }
      }')")
  local http_code
  http_code=$(echo "$resp" | tail -n 1)
  if [[ "$http_code" == "200" || "$http_code" == "201" ]]; then
    log "  Page '${title}' created (HTTP $http_code)."
  else
    log "  WARNING: page '${title}' returned HTTP $http_code — may already exist or failed."
  fi
}

write_env() {
  local pat
  pat=$(echo -n "${ADMIN_USER}:${ADMIN_PASS}" | base64)
  local env_file
  env_file="$(dirname "$0")/../.env"
  log "Writing .env to ${env_file}..."
  cat > "$env_file" <<EOF
# Generated by k8s/setup-confluence.sh — $(date -u +%Y-%m-%dT%H:%M:%SZ)
# Local Confluence Data Center on Docker Desktop k8s

CONFLUENCE_BASE_URL=http://localhost:30090
# HTTP Basic auth encoded as Base64 (admin:admin). The scraper sends this as
# "Authorization: Bearer <value>" which Confluence Data Center accepts for
# Basic auth when the value is a base64-encoded user:password pair.
# For a proper PAT, mint one at:
#   http://localhost:30090/plugins/personalaccesstokens/usertokens.action
CONFLUENCE_PAT=${pat}
CONFLUENCE_SPACE_KEY=${SPACE_KEY}
EOF
  log ".env written."
}

# ─── Main ────────────────────────────────────────────────────────────────────

log "=========================================="
log "Confluence post-license setup automation"
log "=========================================="

wait_for_confluence
create_space

# ─── Page: Kafka Guide ────────────────────────────────────────────────────────
KAFKA_BODY='<h1>Apache Kafka — Team Penta Operational Guide</h1>
<h2>Getting Started</h2>
<p>Apache Kafka is a distributed streaming platform built around a commit log. Data is organised into <strong>topics</strong>, partitioned for parallelism, and replicated for fault-tolerance. Producers write records to topic partitions; consumers subscribe and process records independently via consumer groups.</p>
<h3>Key Concepts</h3>
<ul>
  <li><strong>Topic</strong>: Named stream of records. Partitioned and replicated.</li>
  <li><strong>Partition</strong>: Ordered, immutable sequence of records within a topic. Unit of parallelism.</li>
  <li><strong>Consumer Group</strong>: Set of consumers sharing a group ID. Each partition is consumed by exactly one member per group.</li>
  <li><strong>Offset</strong>: Sequential ID per record per partition. Consumers track their position by committing offsets.</li>
  <li><strong>Broker</strong>: A Kafka server. A cluster has N brokers; partitions are distributed across them.</li>
  <li><strong>Replication Factor</strong>: Number of copies of each partition across different brokers. Recommended minimum: 3 for production.</li>
</ul>
<h2>Common Configuration Pitfalls</h2>
<ul>
  <li><strong>retention.bytes / retention.ms not set</strong>: Disk fills up silently. Always configure both per topic based on expected throughput.</li>
  <li><strong>replication.factor=1</strong>: Single point of failure. Never use in production.</li>
  <li><strong>auto.create.topics.enable=true</strong>: Producers silently create topics with default settings (1 partition, rf=1). Disable in production; manage topics explicitly.</li>
  <li><strong>min.insync.replicas &lt; replication.factor/2+1</strong>: Allows writes when quorum is lost; risk of data loss on broker failure. Set min.insync.replicas=2 for rf=3.</li>
  <li><strong>Large message sizes without broker/client alignment</strong>: message.max.bytes (broker) must match max.request.size (producer) and fetch.max.bytes (consumer). Mismatch causes MessageSizeTooLargeException.</li>
</ul>
<h2>Strimzi Operator on Kubernetes</h2>
<p>Strimzi provides Kubernetes-native management of Kafka via Custom Resource Definitions (CRDs).</p>
<h3>Installation</h3>
<ac:structured-macro ac:name="code"><ac:parameter ac:name="language">bash</ac:parameter><ac:plain-text-body><![CDATA[
kubectl create namespace kafka
helm repo add strimzi https://strimzi.io/charts/
helm install strimzi-operator strimzi/strimzi-kafka-operator -n kafka
]]></ac:plain-text-body></ac:structured-macro>
<h3>KafkaTopic CR</h3>
<ac:structured-macro ac:name="code"><ac:parameter ac:name="language">yaml</ac:parameter><ac:plain-text-body><![CDATA[
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: orders
  namespace: kafka
  labels:
    strimzi.io/cluster: my-cluster
spec:
  partitions: 12
  replicas: 3
  config:
    retention.ms: "86400000"        # 24 h
    retention.bytes: "1073741824"   # 1 GiB per partition
    min.insync.replicas: "2"
]]></ac:plain-text-body></ac:structured-macro>
<h3>KafkaUser CR (SCRAM-SHA-512)</h3>
<ac:structured-macro ac:name="code"><ac:parameter ac:name="language">yaml</ac:parameter><ac:plain-text-body><![CDATA[
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaUser
metadata:
  name: orders-producer
  namespace: kafka
  labels:
    strimzi.io/cluster: my-cluster
spec:
  authentication:
    type: scram-sha-512
  authorization:
    type: simple
    acls:
      - resource:
          type: topic
          name: orders
          patternType: literal
        operations: [Write, Describe]
]]></ac:plain-text-body></ac:structured-macro>
<h3>Upgrading Strimzi</h3>
<p>Strimzi upgrades must follow the documented rolling upgrade path. Key rules:</p>
<ol>
  <li>Upgrade the Operator first; it will not restart existing clusters immediately.</li>
  <li>Update the <code>spec.kafka.version</code> in the Kafka CR and set <code>spec.kafka.config."inter.broker.protocol.version"</code> to the previous version during the rolling upgrade.</li>
  <li>Once all brokers are on the new version, update inter.broker.protocol.version to match.</li>
</ol>
<h2>Common Operational Issues</h2>
<h3>Consumer Lag</h3>
<p>Monitor lag with <code>kafka-consumer-groups.sh --describe --group &lt;group&gt;</code> or Prometheus/Grafana. High lag indicates consumers are slower than producers. Remediation: scale consumer group, increase partition count, or tune max.poll.records and session.timeout.ms.</p>
<h3>Rebalancing Storms</h3>
<p>Frequent rebalancing (group coordinator logs "Preparing to rebalance") degrades throughput. Causes: consumers leaving/joining due to slow poll loop, short session.timeout.ms, or deployment rolling restarts. Fix: increase session.timeout.ms (up to max.poll.interval.ms), use static group membership (group.instance.id), reduce max.poll.records if processing is slow.</p>
<h3>Out-of-Sync Replicas (ISR Shrink)</h3>
<p>ISR shrink means a follower has fallen behind. Check <code>kafka.server:type=ReplicaManager,name=UnderReplicatedPartitions</code> metric. Causes: broker GC pauses, network saturation, disk I/O spikes. If a partition has 0 ISR and all replicas are offline, it is unrecoverable without leader election tricks (unclean.leader.election.enable=true — use with caution, risk of data loss).</p>'

create_page "Kafka Guide" "$KAFKA_BODY"

# ─── Page: Redis Guide ────────────────────────────────────────────────────────
REDIS_BODY='<h1>Redis — Team Penta Operational Guide</h1>
<h2>Redis Fundamentals</h2>
<p>Redis is an in-memory data structure store supporting persistence, replication, and clustering. Core data types:</p>
<ul>
  <li><strong>String</strong>: Binary-safe, up to 512 MB. Used for counters, cached values, session tokens.</li>
  <li><strong>Hash</strong>: Field-value map, ideal for representing objects.</li>
  <li><strong>List</strong>: Linked list of strings. Used for queues (LPUSH/RPOP) and activity feeds.</li>
  <li><strong>Set</strong>: Unordered unique strings. Used for tagging, unique visitor counts.</li>
  <li><strong>Sorted Set (ZSet)</strong>: Set with float scores. Used for leaderboards, rate limiting.</li>
  <li><strong>Stream</strong>: Append-only log with consumer groups. Kafka-like messaging inside Redis.</li>
</ul>
<h3>Persistence Modes</h3>
<ul>
  <li><strong>RDB (Snapshotting)</strong>: Point-in-time snapshots triggered by BGSAVE or SAVE. Compact, but may lose recent writes (RPO = time since last snapshot).</li>
  <li><strong>AOF (Append-Only File)</strong>: Logs every write command. Replayed on restart. appendfsync=everysec balances durability and performance.</li>
  <li><strong>RDB + AOF</strong>: Recommended for most production workloads. AOF used for replay; RDB for faster restarts.</li>
  <li><strong>No persistence</strong>: Pure cache mode. Acceptable when Redis is a cache-aside layer with a backing store.</li>
</ul>
<h2>Redis Sentinel</h2>
<p>Sentinel provides automatic failover for a primary–replica Redis setup. A minimum of 3 Sentinel processes (quorum=2) is required to avoid split-brain.</p>
<h3>Sentinel Setup (sentinel.conf excerpt)</h3>
<ac:structured-macro ac:name="code"><ac:parameter ac:name="language">conf</ac:parameter><ac:plain-text-body><![CDATA[
sentinel monitor mymaster 10.0.0.10 6379 2
sentinel down-after-milliseconds mymaster 5000
sentinel failover-timeout mymaster 60000
sentinel parallel-syncs mymaster 1
]]></ac:plain-text-body></ac:structured-macro>
<h3>Failover Flow</h3>
<ol>
  <li>Sentinels detect primary unreachable (SDOWN) after down-after-milliseconds.</li>
  <li>Once quorum Sentinels agree: ODOWN (objective down).</li>
  <li>Leader Sentinel selects a replica based on priority and replication offset.</li>
  <li>Promoted replica becomes the new primary; remaining replicas reconfigure to replicate from it.</li>
  <li>Old primary rejoins as a replica if/when it recovers.</li>
</ol>
<h3>Common Sentinel Issues</h3>
<ul>
  <li><strong>Quorum not reached</strong>: Fewer Sentinels than quorum are alive; no failover occurs. Always run 3+ Sentinels on different hosts.</li>
  <li><strong>Flapping (false positives)</strong>: Short down-after-milliseconds causes spurious failovers under GC pauses. Use 5000–30000 ms depending on SLA.</li>
  <li><strong>Client not reconnecting to new primary</strong>: Clients must support Sentinel-aware connection (e.g., redis-py Sentinel, Jedis SentinelPool). Hard-coded host:port will break on failover.</li>
</ul>
<h2>Redis Cluster vs Sentinel Trade-offs</h2>
<table>
  <tr><th>Aspect</th><th>Sentinel</th><th>Cluster</th></tr>
  <tr><td>Sharding</td><td>No (single primary)</td><td>Yes (16384 hash slots across N primaries)</td></tr>
  <tr><td>Failover</td><td>Automatic via Sentinel quorum</td><td>Automatic via cluster gossip</td></tr>
  <tr><td>Multi-key ops</td><td>All keys available</td><td>Only if keys hash to same slot (use {tag})</td></tr>
  <tr><td>Minimum nodes</td><td>3 Sentinels + 1 primary + 1 replica</td><td>6 (3 primary + 3 replica minimum)</td></tr>
  <tr><td>Client complexity</td><td>Sentinel-aware client</td><td>Cluster-aware client with MOVED/ASK handling</td></tr>
  <tr><td>Use when</td><td>Dataset fits single node; simplicity preferred</td><td>Dataset &gt; single node memory; horizontal scaling needed</td></tr>
</table>
<h2>Common Operational Issues</h2>
<h3>Memory Eviction</h3>
<p>When maxmemory is reached, Redis evicts keys based on maxmemory-policy. For cache workloads: allkeys-lru or allkeys-lfu. For session stores where no key should be silently dropped: noeviction (causes errors on new writes). Monitor evicted_keys metric; spikes indicate memory pressure.</p>
<h3>Connection Pool Exhaustion</h3>
<p>Redis is single-threaded for command processing. Large connection pools waste memory; too few cause timeouts. Tune pool size to max_connections = (num_app_threads * avg_concurrent_redis_ops). Use connection pipelining and MULTI/EXEC for bulk operations. Enable tcp-keepalive 300 to detect dead connections.</p>
<h3>READONLY Errors During Failover</h3>
<p>During Sentinel failover, the old primary becomes a replica and starts rejecting writes with READONLY. Clients must catch this error and reconnect via Sentinel to discover the new primary. Implement exponential backoff retry logic around Redis write operations. Typical failover window: 5–30 seconds depending on configuration.</p>'

create_page "Redis Guide" "$REDIS_BODY"

# ─── Page: Zookeeper Guide ────────────────────────────────────────────────────
ZK_BODY='<h1>Apache ZooKeeper — Team Penta Operational Guide</h1>
<h2>Role in Distributed Systems</h2>
<p>ZooKeeper is a distributed coordination service providing:</p>
<ul>
  <li><strong>Distributed configuration management</strong>: Storing small configuration blobs shared across a cluster.</li>
  <li><strong>Naming and discovery</strong>: Service registration in znodes.</li>
  <li><strong>Distributed locking and leader election</strong>: Ephemeral sequential znodes implement mutually exclusive locks.</li>
  <li><strong>Barrier synchronisation</strong>: Coordinating phases of a distributed algorithm.</li>
</ul>
<p>In the Kafka ecosystem (pre-KRaft), ZooKeeper stores broker metadata, topic configurations, partition leader assignments, and consumer group offsets (legacy, now stored in an internal Kafka topic).</p>
<h2>ZooKeeper Quorum and Leader Election</h2>
<p>A ZooKeeper ensemble requires a <strong>majority quorum</strong> (⌊N/2⌋+1 nodes) to be available for reads and writes. Typical sizes: 3 (tolerates 1 failure), 5 (tolerates 2 failures).</p>
<h3>Leader Election Protocol (ZAB)</h3>
<ol>
  <li>On startup or leader loss, all servers enter LOOKING state.</li>
  <li>Each server votes for the candidate with the highest epoch+transaction ID (zxid).</li>
  <li>Once a candidate receives a quorum of votes, it becomes the new leader and starts a synchronisation round (SYNC phase) to ensure all followers have the latest committed data.</li>
  <li>After SYNC, the leader enters BROADCAST phase; normal client operations resume.</li>
</ol>
<p>Typical leader election takes 10–30 seconds. During election, all writes are rejected (CONNECTING state in clients).</p>
<h2>Common Operational Issues</h2>
<h3>Session Expiry</h3>
<p>ZooKeeper sessions expire when a client fails to send a heartbeat within the session timeout (tickTime * minSessionTimeout multiplier, default 2*tickTime to 20*tickTime). Expired sessions drop all ephemeral znodes, which can trigger cascading failover in dependent services (e.g., Kafka broker de-registration). Symptoms: "SessionExpiredException" in client logs. Remediation: increase sessionTimeout on client, reduce GC pauses, ensure network latency is below 1/3 of sessionTimeout.</p>
<h3>Split-Brain</h3>
<p>Split-brain occurs when the ensemble partitions and two sub-groups each believe they form a quorum. ZooKeeper's majority-quorum requirement prevents this: only the partition with &gt;N/2 nodes can elect a leader. The minority partition rejects all writes. However, if a firewall rule blocks ZooKeeper port (2181/2888/3888) between AZs asymmetrically, the minority-side clients will block indefinitely rather than fail fast. Configure client sessionTimeout and connectTimeout defensively.</p>
<h3>Disk I/O Saturation</h3>
<p>ZooKeeper writes to its transaction log (dataLogDir) on every transaction — this is synchronous (fsync). Placing the log on a shared disk with other high-write workloads (e.g., application logs, Kafka logs) degrades ZooKeeper latency severely. Best practice: dedicate a separate SSD for ZooKeeper dataLogDir and keep dataDir (snapshots) on a different disk. Monitor: zk_avg_latency &gt; 10ms is a warning sign; &gt;50ms often correlates with client session timeouts.</p>
<h2>Deprecation: Kafka KRaft Mode</h2>
<p>Apache Kafka 3.3+ supports <strong>KRaft (Kafka Raft Metadata mode)</strong>, which eliminates the ZooKeeper dependency entirely. Kafka brokers and controllers manage metadata internally using the Raft consensus algorithm.</p>
<h3>Migration Path</h3>
<ol>
  <li>Kafka 2.8–3.2: ZooKeeper mode only; KRaft available as preview.</li>
  <li>Kafka 3.3–3.6: KRaft production-ready for new clusters; ZooKeeper clusters can continue.</li>
  <li>Kafka 3.7+: ZooKeeper mode deprecated; migration tooling (kafka-storage.sh, migration mode) available.</li>
  <li>Kafka 4.0+: ZooKeeper mode removed entirely.</li>
</ol>
<p>For new Kafka deployments on Strimzi, use <code>spec.kafka.metadataVersion</code> and set <code>spec.zookeeper</code> to absent. Existing ZooKeeper clusters should plan migration before upgrading past 3.7.</p>'

create_page "Zookeeper Guide" "$ZK_BODY"

# ─── Page: Vault Guide ────────────────────────────────────────────────────────
VAULT_BODY='<h1>HashiCorp Vault — Team Penta Operational Guide</h1>
<h2>Core Concepts</h2>
<h3>Secrets Engines</h3>
<p>Vault secrets engines store, generate, or encrypt data. Each engine is mounted at a path:</p>
<ul>
  <li><strong>KV v2</strong> (<code>secret/</code>): Versioned key-value store. Supports soft-delete, metadata, and check-and-set writes.</li>
  <li><strong>Database</strong>: Generates dynamic, short-lived database credentials. Supports PostgreSQL, MySQL, MongoDB, and more.</li>
  <li><strong>AWS / GCP / Azure</strong>: Issues cloud provider credentials (IAM roles, service accounts) on demand.</li>
  <li><strong>PKI</strong>: Acts as a Certificate Authority; issues X.509 certificates with configurable TTL.</li>
  <li><strong>Transit</strong>: Encryption-as-a-service. Data never leaves Vault; only encrypted/decrypted ciphertext is exchanged.</li>
</ul>
<h3>Auth Methods</h3>
<ul>
  <li><strong>Kubernetes</strong>: Pods authenticate using their ServiceAccount JWT; Vault validates against the Kubernetes API.</li>
  <li><strong>AppRole</strong>: Application-to-Vault authentication using RoleID + SecretID. Used for CI/CD pipelines.</li>
  <li><strong>LDAP / OIDC</strong>: Human user authentication integrated with corporate identity providers.</li>
  <li><strong>Token</strong>: Root tokens and child tokens; used for bootstrapping and administrative access.</li>
</ul>
<h3>Policies</h3>
<p>Vault policies are HCL or JSON files defining <code>path</code> + <code>capabilities</code> rules. Capabilities: create, read, update, delete, list, sudo, deny. Example:</p>
<ac:structured-macro ac:name="code"><ac:parameter ac:name="language">hcl</ac:parameter><ac:plain-text-body><![CDATA[
path "secret/data/penta/*" {
  capabilities = ["create", "read", "update", "delete", "list"]
}
path "database/creds/orders-db-role" {
  capabilities = ["read"]
}
path "sys/leases/renew" {
  capabilities = ["update"]
}
]]></ac:plain-text-body></ac:structured-macro>
<h2>Deploying Vault on Kubernetes</h2>
<h3>Helm Installation</h3>
<ac:structured-macro ac:name="code"><ac:parameter ac:name="language">bash</ac:parameter><ac:plain-text-body><![CDATA[
helm repo add hashicorp https://helm.releases.hashicorp.com
kubectl create namespace vault

# HA with integrated storage (Raft)
helm install vault hashicorp/vault -n vault \
  --set server.ha.enabled=true \
  --set server.ha.replicas=3 \
  --set server.ha.raft.enabled=true \
  --set server.affinity="" \
  --set injector.enabled=true
]]></ac:plain-text-body></ac:structured-macro>
<h3>Auto-Unseal with Kubernetes (Transit Seal)</h3>
<p>Vault encrypts its master key using a seal mechanism. In Kubernetes, two options:</p>
<ul>
  <li><strong>AWS KMS / GCP CKMS auto-unseal</strong>: Master key encrypted by a cloud KMS. Vault unseals automatically on restart. Recommended for production.</li>
  <li><strong>Transit unseal</strong>: A separate "root" Vault cluster unseals child Vault clusters via the Transit secrets engine. Useful in air-gapped environments.</li>
</ul>
<ac:structured-macro ac:name="code"><ac:parameter ac:name="language">hcl</ac:parameter><ac:plain-text-body><![CDATA[
# values.yaml snippet for AWS KMS auto-unseal
server:
  extraEnvironmentVars:
    VAULT_SEAL_TYPE: awskms
    VAULT_AWSKMS_SEAL_KEY_ID: "arn:aws:kms:us-east-1:123456789012:key/abcd-1234"
]]></ac:plain-text-body></ac:structured-macro>
<h2>Common Operational Issues</h2>
<h3>Sealed State After Pod Restart</h3>
<p>Vault seals itself (encrypts the master key) on every restart. Without auto-unseal, a human operator must run <code>vault operator unseal</code> with enough unseal key shares (default 3 of 5) to reconstruct the master key. To diagnose: <code>kubectl exec -n vault vault-0 -- vault status</code>. Remediation for on-prem: implement Transit auto-unseal or store unseal keys in a secrets manager accessed at startup via an init container.</p>
<h3>Token Renewal Failures</h3>
<p>Vault tokens have a TTL and a max TTL. Tokens must be explicitly renewed (vault token renew) before expiry; once the max TTL is reached, the token cannot be renewed and a new one must be obtained. Symptoms in applications: "permission denied" or "403 Forbidden" appearing periodically. Remediation: use the Vault Agent (see below) which handles renewal automatically, or implement token renewal in the application using the sys/leases/renew endpoint.</p>
<h3>Audit Log Flooding</h3>
<p>Vault writes an audit log entry for every request and response. High-frequency dynamic credential generation (e.g., a new DB credential per HTTP request) can flood audit logs and fill disk. Remediation: increase lease TTL for database credentials (e.g., 1h instead of 1m), enable credential caching in Vault Agent, and monitor audit log disk usage.</p>
<h2>Vault Agent Injector</h2>
<p>The Vault Agent Injector is a Kubernetes mutating webhook that injects a Vault Agent sidecar into annotated pods. The agent authenticates to Vault, fetches secrets, and writes them to a shared volume accessible by the main container.</p>
<h3>Pod Annotations</h3>
<ac:structured-macro ac:name="code"><ac:parameter ac:name="language">yaml</ac:parameter><ac:plain-text-body><![CDATA[
annotations:
  vault.hashicorp.com/agent-inject: "true"
  vault.hashicorp.com/role: "orders-app"
  vault.hashicorp.com/agent-inject-secret-config.env: "secret/data/penta/orders-app"
  vault.hashicorp.com/agent-inject-template-config.env: |
    {{- with secret "secret/data/penta/orders-app" -}}
    export DB_PASSWORD="{{ .Data.data.db_password }}"
    export API_KEY="{{ .Data.data.api_key }}"
    {{- end }}
]]></ac:plain-text-body></ac:structured-macro>
<p>Secrets are written to <code>/vault/secrets/config.env</code> inside the pod. The main container sources this file or reads it directly. The agent handles token renewal and secret rotation transparently.</p>'

create_page "Vault Guide" "$VAULT_BODY"

# ─── Write .env ───────────────────────────────────────────────────────────────
write_env

log ""
log "=========================================="
log "Setup complete!"
log "  Confluence URL  : ${BASE_URL}"
log "  Admin user      : ${ADMIN_USER}"
log "  Admin password  : ${ADMIN_PASS}"
log "  Space           : ${SPACE_KEY} (${SPACE_NAME})"
log "  Pages created   : Kafka Guide, Redis Guide, Zookeeper Guide, Vault Guide"
log "  .env file       : $(realpath "$(dirname "$0")/../.env")"
log "=========================================="
log ""
log "Next step: run the scraper:"
log "  cd core && node scripts/scrape-confluence.js --space ${SPACE_KEY}"
